### ISSUE TITLE
PHP 7.2 Throws Error on sizeOf()

### ISSUE THREAD

**Issue by Ruaphoc** [austinheap/wordpress-security-txt#8]
Running PHP 7.2, getting an error due to the use of "sizeOf()" against a non-countable variable in class-wordpress-security-txt-public.php.

Line 234 replace "sizeOf()" with "strlen()" to make it work with PHP 7.2.

`header('Content-Length: ' . sizeof($output));`
Becomes:
`header('Content-Length: ' . strlen($output));`

**Comment by austinheap** [comment]
Thank @Ruaphoc, I'll publish an update soon.
